# Rate limiting configuration
$imjournalRatelimitInterval 10
$imjournalRatelimitBurst 20000

# Log format template
template (name = "textLogTemplate" type = "list") {
    property (name = "timestamp" dateFormat = "rfc3339")
        constant (value = " ")
        property (name = "hostname")
        constant (value = " ")
        property (name = "syslogtag")
        property (name = "msg" spifno1stsp = "on")
        property (name = "msg" droplastlf = "on") constant (value = "\n")
}

# Turn off rate limiting for Kamailio logs, Some version does not support SystemLogRateLimitInterval, Comment out.
#$SystemLogRateLimitInterval 0 
$RepeatedMsgReduction off

# Route local0 facility to Kamailio log file
local0.*       -/var/log/kamailio/kamailio.log; textLogTemplate
local0.* stop
